spring.application.name=urlshortener

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=aadityaa17
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8080